server:
  port: 8081

spring:
  application:
    name: iot-data-simulator

logging:
  level:
    com.iot.telemetry.simulator: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Simulator configuration
simulator:
  generation:
    enabled: true
    interval: 5000  # 5 seconds
  users:
    count: 3
  features:
    - login
    - dashboard
    - profile
    - settings
    - checkout
    - search
    - product_details
    - cart
    - payment
    - help

  # Ingestion service configuration
  ingestion:
    url: http://localhost:8082
    
  # Retry configuration
  retry:
    maxAttempts: 3
    delay: 1000  # 1 second