server:
  port: 8082

spring:
  application:
    name: iot-ingestion-service
  
  datasource:
    url: jdbc:h2:mem:telemetrydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.iot.telemetry.ingestion: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Kafka Configuration
kafka:
  bootstrap-servers: localhost:9092
  topic:
    telemetry: telemetry-data
  producer:
    acks: all
    retries: 3
    enable-idempotence: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

ingestion:
  service:
    name: "IoT Telemetry Ingestion Service"
    version: "1.0.0"
    description: "Service for ingesting and storing IoT telemetry data"