server:
  port: 8084

spring:
  application:
    name: iot-time-series-service
  
  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_analytics
    username: postgres
    password: praveenrs01
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop  # Auto-create tables for development
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# InfluxDB Configuration
influxdb:
  url: http://localhost:8086
  token: my-super-secret-auth-token
  org: iot-telemetry
  bucket: telemetry-data

# Logging Configuration
logging:
  level:
    com.iot.telemetry.timeseries: INFO
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always