server:
  port: 8083

spring:
  application:
    name: iot-stream-processor

# Kafka Configuration
kafka:
  bootstrap-servers: localhost:9092
  topic:
    telemetry: telemetry-data
  consumer:
    group-id: stream-processor
    auto-offset-reset: earliest
    enable-auto-commit: true
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Logging Configuration
logging:
  level:
    com.iot.telemetry.processor: INFO
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics